# -*- coding: utf-8 -*-
"""Reiman

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15uZFJde_2JDgVlhix-TAQekwETgZqLHj
"""

import numpy as np
import matplotlib.pyplot as plt
def func(x):
    return(x**2)*np.exp(-x)
a = 1.0
b = 10.0
n = 10

x = np.linspace(a,b,n)
dx = (x[-1]-x[0])/(n-1)

hasil = 0
for i in range(n-1):
    hasil += dx*func(x[i])

xp = np.linspace(a,b)
plt.plot(xp,func(xp))
for i in range (n-1):
    plt.bar(x[i],func(x[i]), align = 'edge', width=dx, color = 'yellow', edgecolor='blue')
plt.show()

print(hasil)